### ISSUE TITLE
Instead of the transparent default, an image placeholder could be better

### ISSUE THREAD

**Issue by tudorpavel** [lafeber/world-flags-sprite#25]
Something like this:

![flag-placeholder](https://cloud.githubusercontent.com/assets/2506871/3614621/d463590a-0dc1-11e4-99c5-c2a0819494e2.png)

I will probably do this for one of my projects. Let me know if you want me to submit a PR with the new image(s).

**Comment by marcolino** [comment]
+1

**Comment by lafeber** [comment]
:+1: Super late reply, but a pull request for this will be appreciated!

**Comment by tudorpavel** [comment]
@lafeber, it's ready for review. :grin:
