### ISSUE TITLE
Great! can we combine three flags?

### ISSUE THREAD

**Issue by seansan** [lafeber/world-flags-sprite#32]
For examle we want to list german speaking countries

So we select Germany, Switzerland and Austria 

Would we great if we can do this with one selector or one selector used with three country codes

Also maybe think of minimum length (say 3 flags wide) for when building a list of languages and some have 1, 2 or 3 flags

**Comment by maskott** [comment]
This kind of functionality could be built in with your own site-specific CSS. No need to bloat the original repo with extraneous features, IMO.

**Comment by lafeber** [comment]
I agree with you @maskott !
