### ISSUE TITLE
Update README.md URL to point to proper CSS include location

### ISSUE THREAD

**Issue by SeanJanis** [lafeber/world-flags-sprite#51]
Looks like this is no longer working: https://cloud.github.com/downloads/lafeber/world-flags-sprite/flags32.css

Please update to: https://github.com/downloads/lafeber/world-flags-sprite/flags32.css

**Comment by aloxe** [comment]
pull request # #52 answers this.

**Comment by lafeber** [comment]
@aloxe @SeanJanis Thank you! It's merged.
